### ISSUE TITLE
CSRF tokens should not require a HTTP session

### ISSUE THREAD

**Issue by chkal** [mvc-spec/ozark#104]
Currently CSRF tokens are stored in the user session. That makes it impossible to use CSRF tokens in stateless applications. We should explore alternative ways that don't require a HTTP session.

Also see #91 reported by @rahmanusta.

**Comment by jeyvison** [comment]
Hey @chkal , as every request includes the CSRF token, we could use a **ContextHolder**(a ThreadLocal Wrapper) to make it avalible to the programmer if he/she needs it. We can intercept the request in the beginning and populate this ContextHolder with token. What you think?

**Comment by chkal** [comment]
You can access the token via `MvcContext`. So I don't think there is a need for any ContextHolder or something like that. See: https://static.javadoc.io/javax.mvc/javax.mvc-api/1.0-edr2/javax/mvc/security/Csrf.html

**Comment by jeyvison** [comment]
Huumm. The bean is session scoped and that's the problem right?
Is there a point where we store it in the httpSession or the annotation does the job alone? Maybe we should consider something like jcache to store the token.

**Comment by chkal** [comment]
The problem is that currently the token is stored in the session, correct. But there are alternative ways to prevent CSRF attacks which don't require server state. One could for example store the token in a client cookie. See: https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)_Prevention_Cheat_Sheet

**Comment by jeyvison** [comment]
>One could for example store the token in a client cookie.

That`s right. I think thats how Spring security handles it. We could store in a cookie but for what I`ve seen many folks are storing as a metatag in the page and sending it in every request.

**Comment by chkal** [comment]
Why are they storing it in a metatag? To access it from JavaScript?

**Comment by jeyvison** [comment]
That`s right. They do that so they can send it as a header value in their requests.

**Comment by chkal** [comment]
Ok, got it. However, that's not really related to how the server stores the token. IMO there are two popular ways to store the token on the server side: In the session or in a client cookie. And Ozark currently only supports the former.

Do you know if Spring Security supports both ways or just one of them? I'm wondering if supporting both ways makes any sense or not.

**Comment by jeyvison** [comment]
Actually the default implementation of Spring security holds the Csrftoken in httpSession. They provide a way to store it in a cookie too and you can implement CsrfTokenRepository for a custom repository(like redis or others). Maybe we should allow the developer the same flexibility on configure where the token will be stored.

**Comment by chkal** [comment]
Agreed. I'll prepare the corresponding API and move the current code into one implementation of that API. I'll come back to this ticket as soon as this is done.

**Comment by jeyvison** [comment]
Great. Let me know if you need some help

**Comment by chkal** [comment]
I just pushed some major changes for the new CSRF token API. The latest changes also include a new cookie-based CSRF strategy. You can activate it by setting a corresponding config property in your application class like this:

```java
@Override
public Map<String, Object> getProperties() {
    Map<String, Object> map = new HashMap<>();
    map.put(Properties.CSRF_TOKEN_STRATEGY, new CookieCsrfTokenStrategy.Builder().build());
    return map;
}
```

I would be happy to get feedback about the current implementation.

**Comment by jeyvison** [comment]
@chkal , hey, just made a few comments on PR. I have a doubt about the way we can set this property too. It can be only programatic or it could be via a properties file(fir example) too?

**Comment by chkal** [comment]
Currently all configuration of the spec and the RI uses the native JAX-RS configuration mechanism. To be honest, back then I also wasn't too happy about having to configure it this way, but on the other hand all the configuration is more or less static and you would never want to alter the configuration between deployments in different environments or something like that.

However, if you see this as a problem, feel free to start a discussion about this on the spec mailing list.

**Comment by chkal** [comment]
Closing this for now as the corresponding feature has been implemented. If there are any further comments, please either start a discussion on `ozark-dev` or create another issue.

**Comment by querynaut** [comment]
@chkal @jeyvison I stumbled on this by chance (google). It's not enough to store the csrf-token somewhere on the client site (e.g. cookie, meta-tag or form field). You will still have to hold a copy somewhere on the Server (Session/database) to check if it's valid for the user.

**Comment by chkal** [comment]
Well, there are ways to prevent CSRF attacks even without server-side state, see for example:

https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)_Prevention_Cheat_Sheet#Double_Submit_Cookie

**Comment by querynaut** [comment]
@chkal Yes, but that requires that you control _all_ subdomains as cookie values can easily be written from them. I have to admit that I don't know your product and it may be enough for you, I just found this accidentally and glanced over it quickly ;-) If that's the case, I'll keep my mouth shut now ;-) 
Greetings!

**Comment by chkal** [comment]
@querynaut Sure. Thanks for pointing that out. Of course everyone has to balance pros and cons of each strategy before using it. I think the Double Submit Cookie is especially interesting for many people who want to prevent server-side state.
