### ISSUE TITLE
Deployment Guide for Wildfly Servers

### ISSUE THREAD

**Issue by rsoika** [mvc-spec/ozark#123]
First of all, I want to thank you for continuing the MVC project! MVC is in my eyes an important part to evolve the web frameworks in Java EE. 
My main problem since more than one year was to get MVC/Ozark running with Wildfly. Finnally I succeeded with the help of this [blog](http://javaakademie.de/blog/java-ee-8-mvc-ozark-wildfly-tomcat).

I have now written a short readme file summarizing the important steps for the deployment setup in Wildfly. See the attached file:
[ozark_wildfly.txt](https://github.com/mvc-spec/ozark/files/1224653/ozark_wildfly.txt)

You may want to add this guide to the project or create a wiki page?

**Comment by chkal** [comment]
Hey @rsoika,

thanks a lot for your support. I think such a readme is really helpful. Especially for people who would like to experiment with other application servers.

It would be great if we could get this onto the "official" Ozark page. What do you think?

https://www.mvc-spec.org/ozark/

The page source is available on GitHub. Have a look here:

https://github.com/mvc-spec/www.mvc-spec.org

You could send a pull request if you like. What do you think about adding a new section "Documentation" between "Project resources" and "Contribute". The you could add a link "Using Ozark on Glassfish".

BTW: We are currently working on getting Ozark to work with other JAX-RS implementations and we are making good progress. So expect some news soon.

**Comment by Daniel-Dos** [comment]
Hi @rsoika ,

Thank for share  this link, really that is very good, the post is very explanatory.  I had been looking at a post a while ago, but not as detailed as the one you presented.

https://developer.jboss.org/people/mkouba/blog/2016/03/16/testing-ozark-java-ee-8-mvc-on-wildfly-10

@chkal 

I saw in your repository the first works to take the strong tie with Jersey, as was discussed in google groups, in this case would also have to look at the implementation of JAX-RS than TomEE, as it uses Apache CXF.

{  },s

**Comment by chkal** [comment]
Hey @Daniel-Dos,

yes, I'm currently working on splitting the Ozark code into a core and a jersey module. I just opened #124 which introduces the jersey module. After merging this one we just have to move the binding interceptor to the jersey module as well and we should have a Ozark core module which should work fine with other JAX-RS implementations.

I'll ping you all as soon as this is finished.

**Comment by rsoika** [comment]
I added the pull request: https://github.com/mvc-spec/www.mvc-spec.org/pull/13

**Comment by Daniel-Dos** [comment]
Very good @chkal . 

{  },s

**Comment by chkal** [comment]
Closing as mvc-spec/www.mvc-spec.org#13 has been merged. Thanks a lot.

**Comment by chkal** [comment]
Good news everyone. Ozark now basically works with RESTEasy. See more details here:

https://groups.google.com/forum/#!topic/ozark-dev/vA20HbqH_MY

**Comment by rsoika** [comment]
That's great news! 
I have just tested it with my own example under Wildfly 10. It works fine!
Great work!
