### ISSUE TITLE
Adjust package names to match new artifact ids

### ISSUE THREAD

**Issue by chkal** [mvc-spec/ozark#126]
The main package for Ozark is currently `org.glassfish.ozark`. We should change this to `org.mvcspec.ozark` to match our group id naming. We are also not a sub project of Glassfish any more, so the package name update totally makes sense.

**Comment by jeyvison** [comment]
Hello @chkal . This one seems to be pretty easy so i'll submit a pull request for it if you don't mind. The changing will be for all the projects, not only ozark-core right?

**Comment by chkal** [comment]
Hey @jeyvison. Thanks for offering help. But I'll take care of the renaming. I'm just waiting for some pending work to be merged, because this renaming will break all the patches. ;-)

**Comment by jeyvison** [comment]
Ok :)

**Comment by chkal** [comment]
Fixed!
