### ISSUE TITLE
surefire-plugin- Bug/Error

### ISSUE THREAD

**Issue by Daniel-Dos** [mvc-spec/ozark#128]
Hi Guys,

In my attempt to build with the current version, I'm frequently getting this error from the surefire plugin.

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project ozark-core: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?`

`[ERROR] Command was /bin/sh -c cd /home/daniel/git/JSR\'s/mvc-spec/ozark/ozark && /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -jar '/home/daniel/git/JSR\'s/mvc-spec/ozark/ozark/target/surefire/surefirebooter1019438903350791193.jar' '/home/daniel/git/JSR\'s/mvc-spec/ozark/ozark/target/surefire/surefire8895481032071347309tmp' '/home/daniel/git/JSR\'s/mvc-spec/ozark/ozark/target/surefire/surefire_07504035973794216548tmp'`

In that I commented the statement of the plugin in pom.xml and tested again and it completed perfectly. Soon after I did another test with a version other than 2.19.1 is also worked correctly.

Would it be a problem even in the version?

**Comment by chkal** [comment]
Hey @Daniel-Dos. Thanks for reporting. Looks like a Surefire plugin bug or something with your setup.

I just updated Surefire to the latest version 2.20 in 4d43a5dc9d249feb5b0f63db6c01d83ca5e2cb88. Could you check if this still happens?

BTW: If you just want to build the latest version, you can also use `mvn -DskipTests clean install` to skip the tests. That's how I do it. ;-)

**Comment by Daniel-Dos** [comment]
Hello @chkal,

Now it's running smoothly.

I discovered the problem, I was using the following command "mvn clean install -DskipTest", for lack of attention of mine, I did not notice the lack of the "s" at the end. :)

Thank you so much.

**Comment by chkal** [comment]
Great! Thanks for the update!
