### ISSUE TITLE
Controller detection doesn't work on RESTEasy

### ISSUE THREAD

**Issue by chkal** [mvc-spec/ozark#129]
I've started to experiment with using `ozark-core` on Wildfly and ran into the following issue:

Currently the initialization code of Ozark checks if there is at least on controller deployed with the app. This is done by checking the classes returned from `javax.ws.rs.core.Configuraton.getClasses()`. Jersey returns all resource classes here, but RESTEasy only seems to return providers. I'll try to get some clarification for this from the JAX-RS EG.

However, I'm wondering whether this check is really necessary. If somebody includes Ozark in his app, why not always bootstrapping Ozark? Having Ozark deployed to an application server may be a different thing, but even in this case I don't think that registering the Ozark providers will lead to any performance decrease even if there is no MVC controller.

Any thoughts?

**Comment by chkal** [comment]
I basically disabled the controller discovery for now, which means that Ozark is now always initialized. I'll start some discussion about this on the mailing list.

**Comment by chkal** [comment]
IMO we don't really need to auto-detect controllers to decide whether to bootstrap or not. However, if someone thinks this is important -> Patches welcome! :-)

**Comment by gtudan** [comment]
I agree that if you drop ozark into the classpath than you'll probably want to use it, so this feature seems rather unnecessary. Most application servers have their own ways of figuring out what features to enable and don't rely on the implementations.

I don't see an implementation agnostic way to do this, but RestEasy supports something like this through the MethodRegistry https://docs.jboss.org/resteasy/docs/3.0.13.Final/javadocs/org/jboss/resteasy/core/ResourceMethodRegistry.html#getBounded()

**Comment by dmaidaniuk** [comment]
Hi @chkal,

As I said in one of Google Groups discussion actually exists vendor agnostic way how to detect MVC Controller usage in REST application. I will prepare PR with required changes on this weekend.
And I think it is a good tone to not add unwanted behavior to an application if exists a way to prevent this. We can't rely on a fact that user have some jar in his classpath because it could be transient dependency or some other accident addition.

Regards,
Dmytro

**Comment by chkal** [comment]
@dmaidaniuk Ok, great! Looking forward to your PR.

**Comment by dmaidaniuk** [comment]
PR is here: https://github.com/mvc-spec/ozark/pull/140

**Comment by chkal** [comment]
Awesome! Thanks a lot! I'll have a look at it ASAP.

**Comment by chkal** [comment]
Fixed with #140. Thanks a lot!

**Comment by dmaidaniuk** [comment]
@chkal, You're welcome!
