### ISSUE TITLE
RedirectScopeManager doesn't work on RESTEasy

### ISSUE THREAD

**Issue by chkal** [mvc-spec/ozark#130]
Our class `RedirectScopeManager` is a CDI managed bean but uses `@Context` to obtain:

 * HttpServletResponse
 * javax.ws.rs.core.Configuration

However, this seems to be a Jersey specific feature that `@Context` works on CDI beans.

I think we have to get rid of this requirement somehow.

**Comment by chkal** [comment]
Same with `OzarkConfig` :-(

**Comment by rsoika** [comment]
I'm not really deep in the subject. But did you mean the following CDI annotation:

	@javax.ws.rs.core.Context
	private static HttpServletRequest servletRequest; 

I use this often in my Rest Service Beans running with RestEasy. But my beans are annotated as @stateless Session EJBs.

**Comment by chkal** [comment]
Actually `@javax.ws.rs.core.Context` is not a annotation but a JAX-RS annotation. And that's the problem here. Ozark is using `@Context` in plain CDI beans and this only works with Jersey.

**Comment by rsoika** [comment]
ok - and the _OzarkContainerInitializer_ ? Could this class be the hook to store the necessary information into the session?

**Comment by chkal** [comment]
I don't think that we can get access to the JAX-RS context objects. But a `ContainerRequestFilter` should work. I'm already experimenting with this approach.

**Comment by chkal** [comment]
Fixed in 6b1bccd
