### ISSUE TITLE
Update Velocity version

### ISSUE THREAD

**Issue by chkal** [mvc-spec/ozark#136]
The `ozark-velocity` extension is using a very old version of Velocity. But recently version 2.0 was released:

https://velocity.apache.org/news.html#engine20

We should update our dependencies and check if everything works as good as before.

**Comment by Daniel-Dos** [comment]
Hi @chkal 

I'm looking at this issue now.

**Comment by dmaidaniuk** [comment]
Hi @chkal ,

I just made upgrade of velocity core library to version 2.0. And seems it is quite easy to drop dependency to `velocity-tools-view` library which cause dependencies collision in @Daniel-Dos 's PR. I moved required utility class `WebappResourceLoader` directly into extension project.
See my PR for changes: https://github.com/mvc-spec/ozark/pull/142 .

Regards,
Dmytro

**Comment by chkal** [comment]
Thanks! I just merged the PR. Closing this now!
