### ISSUE TITLE
Add support for a default file extension for view names

### ISSUE THREAD

**Issue by chkal** [mvc-spec/ozark#151]
See the following discussion on the mailing list:

https://groups.google.com/forum/#!topic/jsr371-users/3ky4bw_8A0I

I think we should try to implement a minimal version of this requirement in Ozark without mentioning it ins the spec. This makes it an Ozark specific feature which we may  add to the spec later on.

I could imagine a configuration parameter like this:

```java
properties.put(Properties.DEFAULT_VIEW_FILE_EXTENSION, "jsp");
```
And some code similar to this one to apply this default (pseudo code):

```java
if( !viewName.endsWith( "." + defaultViewFileExtension) ) {
    viewName = viewName + "." + defaultViewFileExtension;
}
```

**Comment by dmaidaniuk** [comment]
Hi @chkal,

I'm taking this task for implementation. Will provide pull request soon.

Regards,
Dmytro

**Comment by chkal** [comment]
Thanks a lot, @dmaidaniuk. Looking forward to your pull request.

**Comment by Daniel-Dos** [comment]
Hello,

I have tried to do this issue as mentioned above, I do not know if it is really this, I am committing to my changes and would like some help on this:

1 - I created a new attribute in the Properties class : 

https://github.com/Daniel-Dos/Ozark-integrationTests/blob/master/core/src/main/java/org/mvcspec/ozark/Properties.java#L38

2 - I created a method to return a jsp as default if there was no change of the same via JAx-rs getProperties: 

https://github.com/Daniel-Dos/Ozark-integrationTests/blob/master/core/src/main/java/org/mvcspec/ozark/OzarkConfig.java#L64

3 - I did this to check the possible return of views:

https://github.com/Daniel-Dos/Ozark-integrationTests/blob/master/core/src/main/java/org/mvcspec/ozark/core/ViewResponseFilter.java#L154-L162

**Comment by chkal** [comment]
Thanks @Daniel-Dos. I'll have a deeper look at the code as soon as possible and provide some feedback.

**Comment by dmaidaniuk** [comment]
Thank you @Daniel-Dos! 
Could you make pull request with your all changes so it will be suitable to review them in one place, please? Did you also extend tests for this new functionality?

Regards,
Dmytro

**Comment by chkal** [comment]
@Daniel-Dos You could also simply create a pull request and add "[WIP]" in front of the description. This will simplify reviewing and adding comments to the code. What do you think?

**Comment by Daniel-Dos** [comment]
Hello,

@chkal ,  I'll open a PR for this.

@dmaidaniuk,  in the case of the test, would it be one in the Ozark "test" folder?

thanks .

**Comment by dmaidaniuk** [comment]
@Daniel-Dos, yes. We need to write a new test in a location `https://github.com/mvc-spec/ozark/tree/master/test/returns` I think. Maybe @chkal could advice more proper place if this one is not 100% correct.

Regards,
Dmytro

**Comment by Daniel-Dos** [comment]
Hi @dmaidaniuk , 

cool, I can create a "return2" without the "JSP" extensions.

the way it is posted in the link above (item 3), it does not work for @View and neither for ViewAble, this is because I put a wrong location.

as soon as possible I will send a PR so I can get some help on that.

**Comment by chkal** [comment]
+1 for creating a new `returns2` sample app. This is a separate feature, so a separate test app makes sense.

@Daniel-Dos Maybe we should extract the code that appends the default extension to some `protected static` helper method so we can create unit tests for it. There are quite some edge cases and manipulating the view name by conditionally appending a default extension should be pretty easy to unit test. What do you think?

**Comment by Daniel-Dos** [comment]
Hi @chkal, 

in case, would be : 

```
protected static String  someNameMethod (String viewName) {

  final String defaultExtension = ozarkConfig.getDefaultViewFileExtension();

  if (!viewName.endsWith("." + defaultExtension) && !(viewName.startsWith(REDIRECT)) && ! (viewName.startsWith("/"))) {
    	if (!viewName.contains(".")) {
    		viewName = viewName + "." + defaultExtension;
    	 } else if (view.endsWith(".")) { 
		throw new IllegalArgumentException("invalid format for " + viewName);
    	}
         return viewName;
    }
}
```
and would you call inside some Core unit test?

the weekend, I taking a PR as shown in the link in item 3.

thank you .

**Comment by chkal** [comment]
You could also pass the default extension from `OzarkConfig` into them method. This way it will be easier to unit test. And yes, in this case it could be an unit test in `ozark-core`.

**Comment by Daniel-Dos** [comment]
in case that's what you meant? : 

`if (!viewName.endsWith("." + kConfig.getDefaultViewFileExtension()) &&  ...`

and this protected method would still be in the class `ViewResponseFilter.java`

**Comment by chkal** [comment]
I was thinking about something like:

```java
protected static String appendExtensionIfRequired( String viewName, String defaultExtension ) {
  // returns either 'viewName' or a new view name with the default extension appended
}
```

However, feel free to implement it like you want. I just think that we need some test coverage, because the implementation is not trivial as there are some view names which needs to be ignored (like `redirect:*`).

**Comment by dmaidaniuk** [comment]
Hi @chkal & @Daniel-Dos ,

I just pushed my changes for this ticket. You can look on them in next PR:
https://github.com/mvc-spec/ozark/pull/204

It is still work-in-progress changes. I will cover new logic with unit tests. For now, only smoke integration test available in new test module "def-ext". Feel free to give your feedback and suggestions for my changes.

Regards,
Dmytro

**Comment by Daniel-Dos** [comment]
Hi @dmaidaniuk ,

thanks very much to submit an PR .

**Comment by chkal** [comment]
Hi  @dmaidaniuk! Thanks a lot!

We are currently in the process of releasing the "Proposed Final Draft" version of the spec and a new version of Ozark. But as we are in the middle of that process, we will most likely integrate your changes after the release. So it may take some days for me to review it.

**Comment by chkal** [comment]
Fixed! Thanks to @dmaidaniuk for helping with this.
