### ISSUE TITLE
Running Ozark on Wildfly

### ISSUE THREAD

**Issue by rsoika** [mvc-spec/ozark#166]
To run ozark on wildfly (resteasy) is it now still necessary to add beside the 'javax.mvc-api' dependency another lib for wildfly/ozark? 
I know you did a lot of work to get rid of the need to replace rest-easy with jersey. But now I found maybe to much deprecated examples about that. Can you please point me to a example?

**Comment by chkal** [comment]
Ozark, the MVC RI, works fine on Wildfly. You basically just have to include the MVC API JAR and the Ozark Resteasy module. All the details are described here:

https://www.mvc-spec.org/ozark/docs/install-javaee.html

Let me know if you run into any problem.

**Comment by rsoika** [comment]
Thanks! That was the missing link - now it works. 
This page is hard to find...
Why not putting the links to the Installation Guides on the home page?

**Comment by chkal** [comment]
The page described how to setup the reference implementation Ozark, so we placed it on the Ozark main page:

https://www.mvc-spec.org/ozark/

However, I agree that the site structure should be improved!
