### ISSUE TITLE
ControllerAnnotationTest TCK test failure with CXF

### ISSUE THREAD

**Issue by chkal** [mvc-spec/ozark#169]
The TCK verifies that hybrid controllers are handled correctly. Hybrid controllers are JAX-RS resources for which some resource methods are MVC controllers and others not. The MVC processing should only apply to controller methods, but not to standard resource methods without a controller annotation.

https://github.com/mvc-spec/mvc-tck/blob/c050db27be170ff8fc7f0f41ab61e45c6b69fcc7/tests/src/main/java/org/mvcspec/tck/tests/mvc/controller/annotation/HybridController.java#L23

For some reason this doesn't work on CXF. With CXF even the resource method with doesn't have a controller annotation is processed by Ozark. This shouldn't happen.

```
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ControllerAnnotationTest.controllerHybrid:110 
Expected: a string containing "view2.jsp"
     but: was "<h1>Rendered view #2</h1>"
[INFO] 
[ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 0
```

See the full test here:

https://github.com/mvc-spec/mvc-tck/tree/c050db27be170ff8fc7f0f41ab61e45c6b69fcc7/tests/src/main/java/org/mvcspec/tck/tests/mvc/controller/annotation

Any help with debugging this is welcome.

**Comment by Daniel-Dos** [comment]
@chkal,

what version of TomEE that used ? 

I did a quick test with the latest version of TomEE 7.0.5 (https://github.com/apache/tomee/releases) and got no exception for the two issues #168 and #169 .

**Comment by chkal** [comment]
Let's move the discussion to #169

**Comment by chkal** [comment]
The TCK is run against 7.0.4:

https://github.com/mvc-spec/ozark/blob/6b579c2f331a2f9d23096e4823902d6ae957c44a/tck/pom.xml#L196

But actually this is not about an exception. It is just a test failure. 

The test `ControllerAnnotationTest.controllerHybrid` is failing:

https://github.com/mvc-spec/mvc-tck/blob/0176dbfeff3fb5de04636055aa381dad02db99a4/tests/src/main/java/org/mvcspec/tck/tests/mvc/controller/annotation/ControllerAnnotationTest.java#L107-L110

This means that the result of this method is processed by MVC although it is NOT annotated with `@Controller`:

https://github.com/mvc-spec/mvc-tck/blob/0176dbfeff3fb5de04636055aa381dad02db99a4/tests/src/main/java/org/mvcspec/tck/tests/mvc/controller/annotation/HybridController.java#L32-L36

This is a bug. My guess is that CXF applies the JAX-RS providers packaged with Ozark although the `@Controller` name binding is NOT on the resource method or resource class (but just on another method).

**Comment by Daniel-Dos** [comment]
Hi @chkal, 

I did the test again with tomee 7.0.4 and 7.0.5 as shown below:

Tomee 7.0.4 : 

here is what exactly you mentioned, even without the annotation of @Controller, it does as faith as one.

![tomee704](https://user-images.githubusercontent.com/8139890/42534026-f69d4cea-8461-11e8-9690-ae73df091de6.png)


Tomee 7.0.5 :

Now with version 7.0.5 this does not happen, the output is the same as when I rode the Payara.

![tomee705](https://user-images.githubusercontent.com/8139890/42534139-4b272f10-8462-11e8-8f67-040c76d87302.png)

**Comment by chkal** [comment]
Awesome! So it look like the latest snapshots of 7.0.5 don't have this problem any more! That's great news!

Could you check which which CXF version 7.0.4 and 7.0.5-SNAPSHOT are using? Just locate one of the CXF dependency JARs, unpack it and check the contents of the `META-INF/maven` folder. This should reveal the exact version used. This would be interesting to know. Especially because Liberty has a similar problem, because it is also using CXF.

You could also try to create a pull request to update the TomEE version to 7.0.5-SNAPSHOT. See:

https://github.com/mvc-spec/ozark/blob/master/tck/pom.xml#L196

I guess you will have to add some snapshot repository to the corresponding profile. Not sure where to get the snapshots from.

Thanks for your help with this!

**Comment by Daniel-Dos** [comment]
I lwill look this .

**Comment by Daniel-Dos** [comment]
I found the TomEE SNAPSHOTS repository,

https://repository.apache.org/content/groups/snapshots/org/apache/tomee/server/

Do you find it interesting to upgrade to 8.0.0 instead of 7.0.6?

**Comment by chkal** [comment]
I think we should stick with 7.0.x for now. This is the stable branch and that's what we care about.

BTW: It looks like 7.0.5 will be released really soon. So maybe we should wait a bit with updating the version? This way we won't need to add the snapshot repo

**Comment by Daniel-Dos** [comment]
the version 7.0.5 by the repository of git is already released, it is not available for download.

https://github.com/apache/tomee/releases

**Comment by Daniel-Dos** [comment]
Hi @chkal ,

I unzipped one of the CXF Jar's that in the case was cxf-rt-frontend-jaxrs : 

TOmEE-7.0.4 

[TOMEE-7.0.4 - cxf-rt-frontend-jaxrs](https://gist.github.com/Daniel-Dos/15b08424d0561aa3aa298fe60e5e0cad)

TomEE.7.0.5

[TOMEE-7.0.5 - cxf-rt-frontend-jaxrs](https://gist.github.com/Daniel-Dos/6a8be36104cee2ec7197f8b5f2a5561c)

**Comment by chkal** [comment]
I just found the corresponding upstream issue:

https://issues.apache.org/jira/browse/CXF-7630

So it looks like this issue is fixed in CXF 3.2.2 and 3.1.15.

Unfortunately the latest Liberty version is using CXF 3.2.1, so this issue will still occur there. However, it isn't really a blocker. Hybrid controllers are an exceptional case.

**Comment by Daniel-Dos** [comment]
Hi @chkal,

I think you can close this problem. 

thanks .

**Comment by chkal** [comment]
Yes, your are correct. Sorry, I missed to close this one.
